In [3]:
import numpy as np
import pandas as pd
import scipy.io as scp

In [4]:
def sigmoid(z):
    return 1/(1+ np.exp(-z))

In [5]:
# Cost and gradient of logistic regression with regularization
def costFunction(theta, X, y,lambdaparam):

    m = len(y)
    grad = np.zeros(theta.shape)
    
    cost = np.asscalar(-y.T*np.log(sigmoid(X*theta)) - (np.ones((m,1)) - y).T*np.log(1-sigmoid(X* theta)))
    #J = (1/m)*cost
    theta2 = theta[1:]
    regular = np.asscalar(theta2.T*theta2)
    J = (1/m)*cost + (lambdaparam)/(2*m) * regular ;
    grad = (X.T*(sigmoid(X*theta) - y))/m
    grad[1:] = grad[1:] + (lambdaparam/m)*theta2  
    
    return (J,grad)

In [6]:
def gradientDescent(X,y,theta,num_iter,alpha,lambdaparam):
    for i in range(0,num_iter):
        (cost,grad) = costFunction(theta,X,y,lambdaparam)
        theta = theta - alpha*grad
    return theta

In [34]:
def oneVsAll(X, y, num_labels, lambdaparam):
    m = X.shape[0]
    n = X.shape[1]
     
    all_theta = np.matrix(np.zeros((num_labels, n + 1)))

    X = np.matrix(np.concatenate((np.ones((m, 1)), X),axis = 1))


    initial_theta = np.matrix(np.zeros((n + 1, 1)))
    num_iters = 9000
    alpha = 0.1
    
    for c in range(0,num_labels):
        ynew = (y == c).astype(int)
        optheta = gradientDescent(X, ynew,initial_theta,num_iters,alpha,lambdaparam)
        all_theta[c,:] = optheta.T        
    return all_theta

In [8]:
def predictOneVsAll(all_theta, X):

    m = X.shape[0]
    num_labels = all_theta.shape[0]
    all_theta = np.matrix(all_theta)
    p = np.zeros((m, 1))
    X = np.matrix(np.concatenate((np.ones((m, 1)), X),axis = 1))

    hypothesis = sigmoid(X*all_theta.T)
    p = np.matrix(np.argmax(hypothesis,axis = 1))
    return p


In [17]:
import scipy.io
mat = scp.loadmat('ex3data1.mat')
X = np.matrix(mat['X'])
y = np.matrix(mat['y'])

In [16]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
theta_t = np.matrix([[-2], [-1], [1], [2]])
X_t = np.matrix([[1,0.1,0.6,1.1],
[1,0.2,0.7,1.2],
[1,0.3,0.8,1.3],
[1,0.4,0.9,1.4],
[1,0.5,1,1.5]])
y_t = np.matrix([[1],[0],[1],[0],[1]])
lambda_t = 3

In [12]:
(J,grad) = costFunction(theta_t, X_t, y_t, lambda_t)

In [21]:
y

matrix([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)

In [35]:
lambdaparam = 0.1
num_labels = 10
all_theta = oneVsAll(X, y, num_labels, lambdaparam)


In [36]:
pred = predictOneVsAll(all_theta, X)
pred

matrix([[5],
        [5],
        [8],
        ...,
        [9],
        [9],
        [7]], dtype=int64)

In [26]:
pred2 = pred + 1
pred2

matrix([[ 6],
        [ 6],
        [ 9],
        ...,
        [10],
        [10],
        [ 8]], dtype=int64)

In [40]:
pred == 0
np.size(pred == 0) - np.count_nonzero(pred == 0)

5000

In [37]:
print(np.mean(pred == y))

0.8332
